[package]
name = "bene-tree-reuse-study"
version = "0.1.0"
edition = "2024"

[workspace]

[dependencies]
lib = { path = "../../lib" }
gym = { path = "../../gym" }
battlesnake-game-types = { path = "../../battlesnake-game-types" }
serde_json = "1.0.151"

[profile.release]
opt-level = 3
codegen-units = 16
