[package]
name = "battlesnake-game-types"
version = "0.17.0"
authors = ["Penelope Phippen <penelope@hey.com>", "Corey Alexander <coreyja@gmail.com>"]
edition = "2024"
description = "game types for play.battlesnake.com"
license = "Apache-2.0"
repository = "https://github.com/penelopezone/battlesnake-game-types"
documentation = "https://docs.rs/battlesnake-game-types"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "0.7.8"
serde = { workspace = true, features = ["derive"] }
rand = { workspace = true, features = ["simd_support"] }
itertools = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
pprof = { workspace = true, features = ["flamegraph", "frame-pointer"] }
tracing-subscriber = { workspace = true }
tracing-flame = { workspace = true }

[[bench]]
name = "start_of_game_compact"
harness = false

[[bench]]
name = "pea_eater"
harness = false
