[package]
name = "lib"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "0.7.8"
tracing = { workspace = true }
battlesnake-game-types = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rand = { workspace = true, features = ["simd_support"] }

[dev-dependencies]
criterion = { workspace = true, features = ["html_reports"] }
alloc_tracker = "0.7.10"

[features]
bench = []

[[bench]]
name = "mcts_rollout"
harness = false

[[bench]]
name = "mcts_best_child"
harness = false

[[bench]]
name = "mcts_expand"
harness = false

[[bench]]
name = "mcts_allocations"
harness = false

[[bench]]
name = "food_positions"
harness = false
